version: 0.2
phases:
  install:
    runtime-versions: $runtimepython
       #python: 3.7
       #$runtimepython
  build:
    commands:
      - pip install --upgrade pip
      - pip install boto3
      - pip install pipenv --user
      - pip install awscli aws-sam-cli
      - aws cloudformation package --template-file $samTemplate --s3-bucket $s3bucketname --output-template-file $packageTemplate
artifacts:
  type: zip
  files:
    #- '**/*'
    - $samTemplate
    - $packageTemplate
  discard-paths: yes
