AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM EC2 regions
Globals:
  Function:
    Timeout: 3

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.6 #'{{runtime}}'
      #Environment: 
          #Variables: '{{runtime}}'
      Environment:
        Variables:
          SOME_VAR: !Ref SomeVar
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get
            Parameters:
              SomeVar:
                Type: String

  GetEc2Function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: ec2.lambda_handler
      Runtime: python3.7
      Policies: 
        - AWSLambdaExecute
        - AmazonEC2FullAccess
      Events:
        GetEc2:
          Type: Api
          Properties:
            Path: /Ec2
            Method: post
  

